-- Creación de la tabla exam_scans para almacenar los resultados del procesamiento OMR
CREATE TABLE IF NOT EXISTS exam_scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL,
    exam_id UUID REFERENCES examenes(id),
    student_id UUID,
    group_id UUID,
    image_path TEXT NOT NULL,
    public_url TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'error')),
    result JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    processed_at TIMESTAMPTZ
);

-- Índices para mejorar el rendimiento de las consultas
CREATE INDEX IF NOT EXISTS exam_scans_job_id_idx ON exam_scans(job_id);
CREATE INDEX IF NOT EXISTS exam_scans_exam_id_idx ON exam_scans(exam_id);
CREATE INDEX IF NOT EXISTS exam_scans_status_idx ON exam_scans(status);

-- Políticas RLS para la tabla exam_scans
-- Permitir a los usuarios autenticados ver sus propios escaneos
ALTER TABLE exam_scans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuarios pueden ver escaneos de sus exámenes" 
    ON exam_scans FOR SELECT 
    USING (
        auth.uid() IN (
            SELECT u.id FROM users u
            JOIN examenes e ON e.profesor_id = u.id
            WHERE exam_scans.exam_id = e.id
        )
    );

-- Política para permitir inserciones desde la autenticación de servicio
CREATE POLICY "Service role puede insertar registros" 
    ON exam_scans FOR INSERT 
    WITH CHECK (true);

-- Política para permitir actualizaciones desde la autenticación de servicio
CREATE POLICY "Service role puede actualizar registros" 
    ON exam_scans FOR UPDATE 
    USING (true); 